### ISSUE TITLE
Java Code is automatically generated from workflow (for each task a class) 

### ISSUE THREAD

**Issue by eneufeld** [eclipsesource/coffee-editor#15]
The Generator already exists.

- [x] Show generated stubs #16
- [x] Make a change in the model -> save -> show new class #16
- [x] Edit Java Code with LSP Editor: Implement Task, Show Error Markers and Code Completion #17 

Optional: 
- [x] Run Code on server visualized in console (add main method, no classpath)

**Comment by eneufeld** [comment]
ask Philip and Tobias about this

**Comment by eneufeld** [comment]
use fact that backend and frontend runs on the same machine, but also check how complicated it is to use theia workspace api to get the generated files from the server

**Comment by koegel** [comment]
Add property to enable (disabled by default)
