### ISSUE TITLE
Create new workflow model (activity diagram) from coffee model and edit in graphical editor (GLSP component), Read-only implementation of the diagram in Sprotty

### ISSUE THREAD

**Issue by eneufeld** [eclipsesource/coffee-editor#9]
SubTasks:
- [x] Create a workflow containing actions #10 
- [x] Create decisions and merge nodes and connect them #11

Optional:
- [x] Data Storage #12
- [ ] Property View #13
- [x] Components have actions that can be used as tasks #14

**Comment by eneufeld** [comment]
GLSP is published here:
glsp-theia-extension - https://www.npmjs.com/package/glsp-theia-extension
glsp-sprotty - https://www.npmjs.com/packaglsp-sprottyge/glsp-sprotty
theia-glsp  (sprotty-theia glue code) - https://www.npmjs.com/package/theia-glsp
